// Client-side packaging for the "Custom manual" download: the zip only ever
// contains the one layout/theme/logo/favicon this download actually needs,
// never every brand's/layout's files. `JSZip` is a global provided by
// vendor/jszip.min.js (a plain <script> in generator/index.html).
import { CORE_FILES, LAYOUT_CSS, I18N_FILES, FALLBACK_LOGO, FALLBACK_FAVICON } from './file-manifest.js';
import { rootUrl } from '../paths.js';
import { loadNav, flattenNav, langPath } from '../../nav/nav-config.js';
import { isDarkBackground } from '../theme/contrast.js';
import { renderBlock } from '../content/blocks.js';
import { buildPageShell, relativePrefix } from '../content/page-shell.js';
import { toNavConfig, collectLabels } from '../content/structure.js';

const MIME_EXT = {
  'image/svg+xml': 'svg',
  'image/png': 'png',
  'image/jpeg': 'jpg',
  'image/x-icon': 'ico',
  'image/webp': 'webp',
};

function extFromFile(file) {
  const dot = file.name.lastIndexOf('.');
  if (dot > -1) return file.name.slice(dot + 1).toLowerCase();
  return MIME_EXT[file.type] || 'png';
}

// `path` is project-root-relative, resolved via rootUrl() (js/generator/paths.js).
async function fetchText(path) {
  const res = await fetch(rootUrl(path));
  if (!res.ok) throw new Error(`Could not fetch ${path} (${res.status})`);
  return res.text();
}

async function fetchBuffer(path) {
  const res = await fetch(rootUrl(path));
  if (!res.ok) throw new Error(`Could not fetch ${path} (${res.status})`);
  return res.arrayBuffer();
}

// Fills the base-palette variables into a copy of themes/theme-generic.css.
function buildThemeCustomCss(template, { colors, componentColors = {}, borderRadius, fontHeading, fontBody, logoPath, fontFaces = [] }) {
  const replacements = {
    '--color-primary': colors.primary,
    '--color-secondary': colors.secondary,
    '--color-text': colors.text,
    '--color-bg': colors.bg,
    '--font-heading': fontHeading,
    '--font-body': fontBody,
    '--border-radius': borderRadius,
    '--logo-url': `url('../${logoPath}')`,
  };
  let css = template;
  for (const [variable, value] of Object.entries(replacements)) {
    const re = new RegExp(`(${variable}:)[^;]+;`);
    css = css.replace(re, `$1 ${value};`);
  }
  const facesBlock = fontFaces.length ? fontFaces.join('\n') + '\n\n' : '';
  const colorScheme = isDarkBackground(colors.bg) ? 'dark' : 'light';
  const schemeBlock = `\n\n/* Derived from --color-bg — see themes/theme-schema.md's --color-scheme entry. */\n:root {\n  --color-scheme: ${colorScheme};\n}\n`;
  // Appended as a separate :root rule rather than patched into the
  // template's own component-color block, which lives inside a CSS
  // comment (see themes/theme-generic.css).
  const componentEntries = Object.entries(componentColors);
  const componentBlock = componentEntries.length
    ? `\n\n/* Component colors set in the generator — see themes/theme-schema.md. */\n:root {\n${componentEntries
        .map(([cssVar, value]) => `  ${cssVar}: ${value};`)
        .join('\n')}\n}\n`
    : '';
  return facesBlock + css + schemeBlock + componentBlock;
}

function buildFontFace(family, relativeAssetPath) {
  return `@font-face {\n  font-family: '${family}';\n  src: url('../${relativeAssetPath}');\n}`;
}

function buildBrandsConfig({ productName, layout, langs, logoPath, faviconPath }) {
  const safeName = productName.replace(/'/g, "\\'");
  return `// Generated by the manual generator (generator/index.html): a single custom
// brand, one fixed layout, no theme switcher. See themes/theme-custom.css
// for its colors/fonts and themes/theme-schema.md for what each variable
// controls.
export const BRANDS = {
  custom: {
    label: '${safeName}',
    theme: 'themes/theme-custom.css',
    logo: '${logoPath}',
    favicon: '${faviconPath}',
    layout: '${layout}',
  },
};

export const DEFAULT_BRAND = 'custom';

export const LAYOUTS = ['${layout}'];
export const DEFAULT_LAYOUT = '${layout}';

export const LANGS = [${langs.map((l) => `'${l}'`).join(', ')}];
export const DEFAULT_LANG = 'en';

export const LANG_LABELS = {
  en: 'English',
  pt: 'Português',
  es: 'Español',
};
`;
}

function buildReadme({ productName, layout, langs }) {
  return `# ${productName}

Generated with the White-label manual generator (generator/index.html in
the original template repo).

- Layout: ${layout}
- Languages: ${langs.join(', ')}

## Running it locally

Double-clicking \`index.html\` opens it as \`file://\`, and browsers block
\`fetch()\` of local files under that protocol — the page loads but the
header/nav/footer and page content never appear, since those are all fetched
in. You need to serve this folder over HTTP instead. Pick one:

- **VS Code:** install the "Live Server" extension, then **File → Open
  Folder…** and open this folder itself (not just one file in it) — only
  then does right-clicking \`index.html\` offer "Open with Live Server".
  Opening a single file without opening its folder as a VS Code workspace
  won't show that option.
- **No VS Code:** any static file server works, e.g.:

  \`\`\`
  python3 -m http.server 8000
  \`\`\`

  then open http://localhost:8000/.

## Editing content

- **Change what a page says.** Open the page under \`pages/\` (e.g.
  \`pages/en/menu1/index.html\`) in any text editor and edit the text inside the
  \`<h1>\`, \`<h2>\`, and \`<p>\` tags directly.
- **Rename a menu entry, or header/footer text.** Edit \`i18n/en.json\` (and
  \`i18n/pt.json\` / \`i18n/es.json\` if you kept those languages) — the key
  name says what it's for.
- **Change colors or fonts.** Edit \`themes/theme-custom.css\` — every
  variable has a plain-English comment; \`themes/theme-schema.md\` has the
  full reference.
- **Add a page.** Copy an existing page under \`pages/\` for the boilerplate,
  add an entry to \`nav-config.json\`, and add its \`nav.*\` label to
  \`i18n/*.json\`.

This manual ships with a single brand and a single layout (no selector), and
only the one layout's CSS file — that's the "custom manual" the generator
built for you, not a bug. To switch to a different layout later, copy the
matching \`css/layout-*.css\` file over from the original template repo and
add its \`<link>\` back to each page's \`<head>\`.
`;
}

// Generated fresh (not copied from file-manifest.js) so it always redirects
// to the right default-language page for whichever menu/language
// combination this download actually has.
function buildManualIndexHtml({ defaultLang, faviconPath }) {
  const target = `pages/${defaultLang}/menu1/index.html`;
  return `<!DOCTYPE html>
<html lang="${defaultLang}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Redirecting…</title>
  <link rel="icon" type="image/svg+xml" id="favicon-link" href="${faviconPath}">
  <script type="module">
    const target = new URL('${target}', window.location.href);
    target.search = window.location.search;
    window.location.replace(target.href);
  </script>
</head>
<body>
  <p>Redirecting to the user guide… If nothing happens, <a href="${target}">click here</a>.</p>
</body>
</html>
`;
}

// Matches any of the 4 layout <link> tags, e.g.
// `  <link rel="stylesheet" href="../../../css/layout-navbar.css">\n` —
// capturing the relative-path prefix and the layout name.
const LAYOUT_LINK_RE = /[ \t]*<link rel="stylesheet" href="([^"]*)css\/layout-([a-z]+)\.css">\r?\n/g;

// Strips every layout <link> except the chosen one, and points the theme/
// favicon <link>s at the fixed custom names, so the page never references a
// file this zip doesn't ship.
function rewriteManualPage(html, { layout, faviconExt }) {
  let out = html.replace(LAYOUT_LINK_RE, (whole, _prefix, name) => (name === layout ? whole : ''));
  out = out.replace(/(id="theme-css" href="[^"]*?)theme-generic\.css/, '$1theme-custom.css');
  out = out.replace(/(id="favicon-link" href="[^"]*?assets\/)favicon(?:-custom)?\.[a-z0-9]+/, `$1favicon-custom.${faviconExt}`);
  return out;
}

function filterNavLangs(nav, extraLangs) {
  return nav.map((item) => {
    const next = { ...item };
    if (item.langs) next.langs = item.langs.filter((l) => extraLangs.includes(l));
    if (item.children) next.children = filterNavLangs(item.children, extraLangs);
    return next;
  });
}

function extFromPath(path) {
  const dot = path.lastIndexOf('.');
  return dot > -1 ? path.slice(dot + 1).toLowerCase() : 'svg';
}

function extFromDataUrl(dataUrl) {
  const match = /^data:([^;,]+)/.exec(dataUrl);
  return (match && MIME_EXT[match[1]]) || 'png';
}

async function decodeDataUrlBuffer(dataUrl) {
  const res = await fetch(dataUrl);
  return res.arrayBuffer();
}

// Data URLs can't ship inside the generated HTML (they bloat every page and
// defeat browser caching) — each image/attachment a block references gets
// decoded into a real file under assets/manual-images/ once per manual, and
// the rendered <img src>/<a href> is rewritten to the matching relative
// path. Non-data sources (e.g. a figure imported from an existing demo page,
// still pointing at assets/example-*.svg) are left untouched.
function makeAssetWriter(zip, prefix) {
  let counter = 0;
  return async (dataUrl) => {
    if (!dataUrl || !dataUrl.startsWith('data:')) return dataUrl;
    counter += 1;
    const ext = extFromDataUrl(dataUrl);
    const fileName = `assets/manual-images/img-${Date.now().toString(36)}-${counter}.${ext}`;
    zip.file(fileName, await decodeDataUrlBuffer(dataUrl));
    return `${prefix}${fileName}`;
  };
}

// Renders one edited/new page's HTML from its blocks — used instead of
// fetch+rewriteManualPage() whenever build-package.js's caller (the content
// editor) has an in-memory blocks[] for that item/lang. See the plan's
// "Geracao dos arquivos HTML novos" section.
async function renderEditedPage(zip, { item, lang, layout, page, faviconPath }) {
  const path = item.path.replace('{lang}', lang);
  const prefix = relativePrefix(path);
  const writeAsset = makeAssetWriter(zip, prefix);
  const resolveImageSrc = (block) => writeAsset(block.srcDataUrl);
  const resolveAttachmentHref = (block) => writeAsset(block.href);
  // Each block may need to await its own asset write, so render sequentially
  // rather than reuse blocks.js's synchronous renderPage().
  const rendered = [];
  for (const block of page.blocks) {
    if (block.type === 'figure' && block.srcDataUrl?.startsWith('data:')) {
      const src = await resolveImageSrc(block);
      rendered.push(renderBlock({ ...block, srcDataUrl: src }));
    } else if (block.type === 'attachment' && block.href?.startsWith('data:')) {
      const href = await resolveAttachmentHref(block);
      rendered.push(renderBlock({ ...block, href }));
    } else {
      rendered.push(renderBlock(block));
    }
  }
  const html = buildPageShell({
    path,
    lang,
    title: page.title || item.id,
    layout,
    bodyHtml: rendered.join('\n\n'),
    faviconPath,
  });
  zip.file(path, html);
}

// options.logoFile/faviconFile/customFonts are optional — an omitted logo
// or favicon falls back to this template's own generic-brand asset.
export async function buildManualZip(options) {
  const { colors, componentColors, borderRadius, fontHeading, fontBody, logoFile, faviconFile, productName, layout, langs, customFonts, content } = options;
  const zip = new JSZip();
  const extraLangs = langs.filter((l) => l !== 'en');
  const selectedLangs = ['en', ...extraLangs];
  const logoExt = logoFile ? extFromFile(logoFile) : extFromPath(FALLBACK_LOGO);
  const faviconExt = faviconFile ? extFromFile(faviconFile) : extFromPath(FALLBACK_FAVICON);
  const logoPath = `assets/logo-custom.${logoExt}`;
  const faviconPath = `assets/favicon-custom.${faviconExt}`;

  // print.html is skipped here — it needs its own <link> rewriting below.
  for (const path of CORE_FILES) {
    if (path === 'print.html') continue;
    zip.file(path, await fetchBuffer(path));
  }

  zip.file(LAYOUT_CSS[layout], await fetchBuffer(LAYOUT_CSS[layout]));

  // Custom menu/submenu labels typed in the content editor have no real
  // i18n/*.json entry (see content/structure.js's collectLabels) — merged
  // into each dict here under their synthetic `custom.<id>` key before it's
  // written, so nav-render.js's normal labelKey lookup just finds them.
  const customLabels = content ? collectLabels(content.structure) : {};
  for (const lang of selectedLangs) {
    const path = I18N_FILES[lang];
    const dict = JSON.parse(await fetchText(path));
    dict['product.name'] = productName;
    Object.assign(dict, customLabels[lang]);
    zip.file(path, JSON.stringify(dict, null, 2));
  }

  // Also the source this zip's own page list is derived from below, so it
  // can never drift out of sync with which pages actually ship. When the
  // content editor was used, the nav comes from its live structure (which
  // may have added/removed/reordered menus) instead of the repo's own
  // nav-config.json.
  const nav = content ? toNavConfig(content.structure) : await loadNav();
  zip.file('nav-config.json', JSON.stringify(filterNavLangs(nav, extraLangs), null, 2));

  for (const item of flattenNav(nav)) {
    for (const lang of selectedLangs) {
      if (lang !== 'en' && !(item.langs || []).includes(lang)) continue;
      const editedPage = content?.pages?.[`${item.id}::${lang}`];
      if (editedPage) {
        await renderEditedPage(zip, { item, lang, layout, page: editedPage, faviconPath });
        continue;
      }
      // Reaching here for a custom (editor-created) item with no authored
      // page would mean validate.js's pre-download checklist was skipped —
      // it guarantees every included item has at least English content.
      const path = langPath(item, lang);
      const html = await fetchText(path);
      zip.file(path, rewriteManualPage(html, { layout, faviconExt }));
    }
  }

  const printHtml = await fetchText('print.html');
  zip.file('print.html', rewriteManualPage(printHtml, { layout, faviconExt }));

  const fontFaces = [];
  if (customFonts && customFonts.heading && customFonts.heading.file) {
    const ext = extFromFile(customFonts.heading.file);
    const assetPath = `assets/font-heading-custom.${ext}`;
    zip.file(assetPath, await customFonts.heading.file.arrayBuffer());
    fontFaces.push(buildFontFace(customFonts.heading.family, assetPath));
  }
  if (customFonts && customFonts.body && customFonts.body.file) {
    const ext = extFromFile(customFonts.body.file);
    const assetPath = `assets/font-body-custom.${ext}`;
    zip.file(assetPath, await customFonts.body.file.arrayBuffer());
    fontFaces.push(buildFontFace(customFonts.body.family, assetPath));
  }

  const themeTemplate = await fetchText('themes/theme-generic.css');
  zip.file('themes/theme-custom.css', buildThemeCustomCss(themeTemplate, { colors, componentColors, borderRadius, fontHeading, fontBody, logoPath, fontFaces }));

  zip.file('js/theme/brands-config.js', buildBrandsConfig({ productName, layout, langs, logoPath, faviconPath }));
  zip.file('index.html', buildManualIndexHtml({ defaultLang: 'en', faviconPath }));

  zip.file(logoPath, logoFile ? await logoFile.arrayBuffer() : await fetchBuffer(FALLBACK_LOGO));
  zip.file(faviconPath, faviconFile ? await faviconFile.arrayBuffer() : await fetchBuffer(FALLBACK_FAVICON));

  zip.file('README.md', buildReadme({ productName, layout, langs }));

  return zip.generateAsync({ type: 'blob' });
}
